install: install_basic install_electron install_bootstrap install_jqueryui install_message_boxes install_ace_editor install_pixi install_mnmenu install_jstree

uninstall: uninstall_basic uninstall_electron uninstall_bootstrap uninstall_jqueryui uninstall_message_boxes uninstall_ace_editor uninstall_pixi uninstall_mnmenu uninstall_jstree

install_basic:
	$(MAKE) -C basic install

install_electron:
	$(MAKE) -C electron install

install_bootstrap:
	$(MAKE) -C bootstrap install

install_jqueryui:
	$(MAKE) -C jqueryui install

install_message_boxes:
	$(MAKE) -C message_boxes install

install_ace_editor:
	$(MAKE) -C ace_editor install

install_pixi:
	$(MAKE) -C pixi install

install_mnmenu:
	$(MAKE) -C mnmenu install

install_jstree:
	$(MAKE) -C jstree install

uninstall_basic:
	$(MAKE) -C basic uninstall

uninstall_electron:
	$(MAKE) -C electron uninstall

uninstall_bootstrap:
	$(MAKE) -C bootstrap uninstall

uninstall_jqueryui:
	$(MAKE) -C jqueryui uninstall

uninstall_message_boxes:
	$(MAKE) -C message_boxes uninstall

uninstall_ace_editor:
	$(MAKE) -C ace_editor uninstall

uninstall_pixi:
	$(MAKE) -C pixi uninstall

uninstall_mnmenu:
	$(MAKE) -C mnmenu uninstall

uninstall_jstree:
	$(MAKE) -C jstree uninstall

