install: install_bootstrap install_jqueryui install_message_boxes install_ace_editor install_pixi

uninstall: uninstall_bootstrap uninstall_jqueryui uninstall_message_boxes uninstall_ace_editor uninstall_pixi

install_bootstrap:
	$(MAKE) -C bootstrap install

install_jqueryui:
	$(MAKE) -C jqueryui install

install_message_boxes:
	$(MAKE) -C message_boxes install

install_ace_editor:
	$(MAKE) -C ace_editor install

install_pixi:
	$(MAKE) -C pixi install

uninstall_bootstrap:
	$(MAKE) -C bootstrap uninstall

uninstall_jqueryui:
	$(MAKE) -C jqueryui uninstall

uninstall_message_boxes:
	$(MAKE) -C message_boxes uninstall

uninstall_ace_editor:
	$(MAKE) -C ace_editor uninstall

uninstall_pixi:
	$(MAKE) -C pixi uninstall

